# Generated by Django 3.0.5 on 2021-01-14 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('bird_id', models.AutoField(primary_key=True, serialize=False)),
                ('bird_type', models.CharField(max_length=30)),
                ('bird_name', models.CharField(max_length=30)),
                ('bird_gender', models.CharField(max_length=10)),
                ('bird_color', models.CharField(max_length=30)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bird',
            },
        ),
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('cage_num', models.AutoField(primary_key=True, serialize=False)),
                ('bird_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Bird')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cage',
            },
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeding_date', models.DateTimeField()),
                ('hatch_date', models.DateTimeField()),
                ('bird_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Bird')),
                ('cage_num', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Cage')),
            ],
            options={
                'db_table': 'Breeding',
            },
        ),
    ]
